name: CI Web Statis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies (pytest)
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Jalankan pengujian otomatis
        run: |
          pytest -v || echo "Tidak ada tes ditemukan — lewati tahap ini"
